app/src/Entity/Participation.php
<?php

namespace App\Entity;

use App\Repository\ParticipationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ParticipationRepository::class)]
class Participation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column]
    private ?int $credits_used = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ride $ride = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreditsUsed(): ?int
    {
        return $this->credits_used;
    }

    public function setCreditsUsed(int $credits_used): static
    {
        $this->credits_used = $credits_used;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getRide(): ?Ride
    {
        return $this->ride;
    }

    public function setRide(?Ride $ride): static
    {
        $this->ride = $ride;

        return $this;
    }
}

app/src/Entity/Ride.php
<?php

namespace App\Entity;

use App\Repository\RideRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RideRepository::class)]
class Ride
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $departure_city = null;

    #[ORM\Column(length: 255)]
    private ?string $departure_address = null;

    #[ORM\Column(length: 10)]
    private ?string $departure_post_code = null;

    #[ORM\Column(length: 255)]
    private ?string $arrival_city = null;

    #[ORM\Column(length: 255)]
    private ?string $arrival_address = null;

    #[ORM\Column(length: 10)]
    private ?string $arrival_post_code = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $departure_time = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $arrival_time = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $seats_available = null;

    #[ORM\Column]
    private ?bool $ecological = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $driver = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicle $vehicle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepartureCity(): ?string
    {
        return $this->departure_city;
    }

    public function setDepartureCity(string $departure): static
    {
        $this->departure_city = $departure;

        return $this;
    }
    
    public function getDepartureAddress(): ?string
    {
        return $this->departure_address;
    }

    public function setDepartureAddress(string $departure): static
    {
        $this->departure_address = $departure;

        return $this;
    }

    public function getArrivalCity(): ?string
    {
        return $this->arrival_city;
    }

    public function setArrivalCity(string $arrival): static
    {
        $this->arrival_city = $arrival;

        return $this;
    }

public function getArrivalAddress(): ?string
    {
        return $this->arrival_address;
    }

public function setArrivalAddress(string $arrival): static
    {
        $this->arrival_address = $arrival;

        return $this;
    }

    public function getDepartureTime(): ?\DateTimeImmutable
    {
        return $this->departure_time;
    }

    public function setDepartureTime(\DateTimeImmutable $departure_time): static
    {
        $this->departure_time = $departure_time;

        return $this;
    }

    public function getArrivalTime(): ?\DateTimeImmutable
    {
        return $this->arrival_time;
    }

    public function setArrivalTime(\DateTimeImmutable $arrival_time): static
    {
        $this->arrival_time = $arrival_time;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getSeatsAvailable(): ?int
    {
        return $this->seats_available;
    }

    public function setSeatsAvailable(int $seats_available): static
    {
        $this->seats_available = $seats_available;

        return $this;
    }

    public function isEcological(): ?bool
    {
        return $this->ecological;
    }

    public function setEcological(bool $ecological): static
    {
        $this->ecological = $ecological;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDriver(): ?User
    {
        return $this->driver;
    }

    public function setDriver(?User $driver): static
    {
        $this->driver = $driver;

        return $this;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): static
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    public function getDeparturePostCode(): ?string
    {
        return $this->departure_post_code;
    }
    
    public function setDeparturePostCode(string $departure_post_code): static
    {
        $this->departure_post_code = $departure_post_code;
    
        return $this;
    }

    public function getArrivalPostCode(): ?string
    {
        return $this->arrival_post_code;
    }
    
    public function setArrivalPostCode(string $arrival_post_code): static
    {
        $this->arrival_post_code = $arrival_post_code;
    
        return $this;
    }
}

app/src/Controller/dashboard/AdminDashboardController.php
<?php

namespace App\Controller\dashboard;

use App\Entity\CreditTransaction;
use App\Entity\User;
use App\Form\EmployeType;
use App\Form\RegistrationType;
use App\Repository\CreditTransactionRepository;
use App\Repository\RideRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class AdminDashboardController extends AbstractController
{
    #[Route('/admin/dashboard', name: 'app_dashboard_admin')]
    #[IsGranted('ROLE_ADMIN')]
    public function admin(
        CreditTransactionRepository $creditTransactionRepository,
        RideRepository $rideRepository,
        Request $request
    ): Response {
        $rangeRides = $request->query->getInt('rangeRides', 7);
        $rangeCredits = $request->query->getInt('rangeCredits', 7);

        $ridesPerDay = $rideRepository->countRidesGroupedByDay($rangeRides);
        $labelsRide = array_column($ridesPerDay, 'date');
        $dataRide = array_column($ridesPerDay, 'count');

        $creditsPerDay = $creditTransactionRepository->countCreditsGroupedByDay($rangeCredits);
        $labelsCredit = array_column($creditsPerDay, 'date');
        $dataCredit = array_column($creditsPerDay, 'amount');

        $commissions = $creditTransactionRepository->findBy([
            'reason' => 'Commission'
        ]);
        $refundCommissions = $creditTransactionRepository->findBy([
            'reason' => 'Refund Commission'
        ]);
        $balance = (count($commissions) * 2) - (count($refundCommissions) * 2);
        return $this->render('dashboard/admin/admin.html.twig', [
            'user' => $this->getUser(),
            'balance' => $balance,
            'rideLabels' => $labelsRide,
            'rideCounts' => $dataRide,
            'creditLabels' => $labelsCredit,
            'creditCounts' => $dataCredit,
        ]);
    }

    #[Route('/admin/dashboard/create-employee', name: 'app_create_employee')]
    #[IsGranted('ROLE_ADMIN')]
    public function createEmployee(
        Request $request,
        EntityManagerInterface $em,
        UserPasswordHasherInterface $passwordHasher
    ): Response {
        $user = new User();
        $form = $this->createForm(RegistrationType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plainPassword = $form->get('plainPassword')->getData();
            $hashedPassword = $passwordHasher->hashPassword($user, $plainPassword);
            $user->setPassword($hashedPassword);
            $user->setRoles(['ROLE_EMPLOYE']);
            $user->setSuspended(false);

            $em->persist($user);

            $em->flush();

            $this->addFlash('primary', 'Le compte employé a bien été créé.');
            return $this->redirect($request->headers->get('referer'));
        }

        return $this->render('dashboard/admin/create-employee.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/admin/dashboard/manage-accounts', name: 'app_manage_accounts')]
    #[IsGranted('ROLE_ADMIN')]
    public function manageAccounts(
        UserRepository $userRepository,
        Request $request,
        PaginatorInterface $paginator,
    ): Response {
        $sortUsers = $request->query->get('sortUsers', 'id');
        $directionUsers = $request->query->get('directionUsers', 'asc');

        $sortEmployes = $request->query->get('sortEmployes', 'id');
        $directionEmployes = $request->query->get('directionEmployes', 'asc');

        $searchUsers = $request->query->get('searchUsers', '');
        $searchEmployes = $request->query->get('searchEmployes', '');

        $allowedSorts = ['id', 'pseudo', 'email', 'roles', 'suspended'];
        if (!in_array($sortUsers, $allowedSorts)) $sortUsers = 'id';
        if (!in_array($sortEmployes, $allowedSorts)) $sortEmployes = 'id';

        $queryUsers = $userRepository->createQueryBuilder('u')
            ->where('(u.roles LIKE :role1 OR u.roles LIKE :role2)')
            ->setParameter('role1', '%ROLE_PASSENGER%')
            ->setParameter('role2', '%ROLE_DRIVER%');

        if ($searchUsers !== '') {
            $queryUsers->andWhere('u.pseudo LIKE :searchUsers OR u.email LIKE :searchUsers')
                ->setParameter('searchUsers', '%' . $searchUsers . '%');
        }

        $queryUsers->orderBy('u.' . $sortUsers, $directionUsers);

        $queryEmployes = $userRepository->createQueryBuilder('u')
            ->where('u.roles LIKE :role')
            ->setParameter('role', '%ROLE_EMPLOYE%');

        if ($searchEmployes !== '') {
            $queryEmployes->andWhere('u.pseudo LIKE :searchEmployes OR u.email LIKE :searchEmployes')
                ->setParameter('searchEmployes', '%' . $searchEmployes . '%');
        }

        $queryEmployes->orderBy('u.' . $sortEmployes, $directionEmployes);

        $users = $paginator->paginate($queryUsers, $request->query->getInt('pageUsers', 1), 5);
        $employes = $paginator->paginate($queryEmployes, $request->query->getInt('pageEmployes', 1), 5);

        return $this->render('dashboard/admin/manage-accounts.html.twig', [
            'users' => $users,
            'employes' => $employes,
            'sortUsers' => $sortUsers,
            'directionUsers' => $directionUsers,
            'sortEmployes' => $sortEmployes,
            'directionEmployes' => $directionEmployes,
            'searchUsers' => $searchUsers,
            'searchEmployes' => $searchEmployes,
        ]);
    }
}

app/src/Controller/dashboard/DashboardController.php
<?php

namespace App\Controller\dashboard;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class DashboardController extends AbstractController
{
    private function hasRole(string $role): bool
    {
        return in_array($role, $this->getUser()?->getRoles() ?? [], true);
    }

    #[Route('/dashboard', name: 'app_dashboard')]
    public function index(): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        if ($this->hasRole('ROLE_ADMIN')) {
            return $this->redirectToRoute('app_dashboard_admin');
        }

        if ($this->hasRole('ROLE_EMPLOYE')) {
            return $this->redirectToRoute('app_dashboard_employe');
        }

        if ($this->hasRole('ROLE_DRIVER')) {
            return $this->redirectToRoute('app_dashboard_driver');
        }

        return $this->redirectToRoute('app_dashboard_passager');
    }
}

app/src/Controller/dashboard/EmployeDashboardController.php
<?php

namespace App\Controller\dashboard;

use App\Repository\ReportRepository;
use App\Repository\ReviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class EmployeDashboardController extends AbstractController
{
    #[Route('/employe/dashboard', name: 'app_dashboard_employe')]
    #[IsGranted('ROLE_EMPLOYE')]
    public function employe(
        ReviewRepository $reviewRepository,
        ReportRepository $reportRepository,
    ): Response
    {
        $reviews = $reviewRepository->findBy([
            'validated' => false,
        ]);

        $reports = $reportRepository->findBy([
            'status' => 'pending',
        ]);

        return $this->render('dashboard/employe/employe.html.twig', [
            'user' => $this->getUser(),
            'reviews' => $reviews,
            'reports' => $reports,
        ]);
    }
    #[Route('/employe/dashboard/manage-reviews', name: 'app_manage_reviews')]
    #[IsGranted('ROLE_EMPLOYE')]
    public function manageReviews(
        ReviewRepository $reviewRepository,
    ): Response
    {
        $reviews = $reviewRepository->findBy([
            'validated' => false,
        ]);

        return $this->render('dashboard/employe/manage-reviews.html.twig', [
            'user' => $this->getUser(),
            'reviews' => $reviews,
        ]);
    }
    #[Route('/employe/dashboard/manage-reports', name: 'app_manage_reports')]
    #[IsGranted('ROLE_EMPLOYE')]
    public function manageReports(
        ReportRepository $reportRepository,
    ): Response
    {
        $reports = $reportRepository->findBy([
            'status' => 'pending',
        ]);

        return $this->render('dashboard/employe/manage-reports.html.twig', [
            'user' => $this->getUser(),
            'reports' => $reports,
        ]);
    }
}

app/src/Controller/dashboard/UserDashboardController.php
<?php 

namespace App\Controller\dashboard;

use App\Repository\CreditTransactionRepository;
use App\Repository\ParticipationRepository;
use App\Repository\ReviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class UserDashboardController extends AbstractController
{
    #[Route('/passenger/dashboard', name: 'app_dashboard_passager', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_PASSENGER')]
    public function passager(
        ParticipationRepository $participationRepository,
        CreditTransactionRepository $transactionRepository,
        ReviewRepository $reviewRepository,
    ): Response {
        /** @var \App\Entity\User $user */
        $user = $this->getUser();

        $participationsActive = $participationRepository->findBy([
            'user' => $user,
            'status' => ['active', 'waiting_passenger_review']
        ]);

        $ratingsByDriver = [];

        foreach ($participationsActive as $participation) {
            $driver = $participation->getRide()->getDriver();
            $driverId = $driver->getId();

            if (!isset($ratingsByDriver[$driverId])) {
                $ratingsByDriver[$driverId] = $reviewRepository->getAverageRatingForUser($driver);
            }
        }
        $balance = $transactionRepository->calculateUserBalance($this->getUser());

        return $this->render('dashboard/passager.html.twig', [
            'user' => $this->getUser(),
            'participations_active' => $participationsActive,
            'balance' => $balance,
            'ratings_by_driver' => $ratingsByDriver,
        ]);
    }
}

app/templates/dashboard/employe/employe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord - EcoRde
{% endblock %}

{% block body %}

	<main class="container-xl">

		<div class="d-flex align-items-center mb-3">
			<h1 class="text-dark">
				Tableau de bord - Employé
				<span class="text-primary">{{user}}</span>
			</h1>
        </div>
		<div class="list-group mb-4">
			<div class="fw-bold text-uppercase small text-dark px-3 py-2 border border-bottom-0 rounded-top">Employé</div>
			<a class="list-group-item" href="{{path('app_manage_reviews')}}">Gérer les avis<span class="badge bg-danger ms-2 {{ reviews|length > 0 ? '' : 'd-none'}}">{{ reviews|length }}</span></a>
			<a class="list-group-item" href="{{path('app_manage_reports')}}">Litiges<span class="badge bg-danger ms-2 {{ reports|length > 0 ? '' : 'd-none'}}">{{ reports|length }}</span></a>
		</div>
    </main>

{% endblock %}

app/templates/dashboard/employe/manage-reports.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les litiges - EcoRde
{% endblock %}

{% block body %}

	<main class="container-xl">
		<a href="{{path('app_dashboard')}}" class="btn text-dark">
			<i class="bi bi-arrow-left-circle fs-3"></i>
		</a>
		<h1 class="text-dark">Gérer les litiges</h1>

		<section class="mt-3">
			{% if reports is not empty %}
				<div class="accordion mt-3" id="accordion_reviews">
					{% for report in reports %}
						<div class="accordion-item">
							<h2 class="accordion-header" id="heading-{{ loop.index }}">
								{% set is_first = loop.first %}
								<button class="accordion-button {{ is_first ? '' : 'collapsed'}} text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ loop.index }}" aria-expanded="{{ is_first ? 'true' : 'false' }}" aria-controls="collapse-{{ loop.index }}">
									Rapport trajet numéro
									{{report.participation.ride.id}}
								</button>
							</h2>
							<div id="collapse-{{ loop.index }}" class="accordion-collapse collapse {{ is_first ? 'show' : '' }}" data-bs-parent="#accordion_reviews">
								<div class="accordion-body">
									<div class="row gap-2">
										<div class="col">
											<div class="list-group">
												<div class="fw-bold text-uppercase small text-dark px-3 py-2 border border-bottom-0 rounded-top">Passager</div>
												<div class="text-primary px-3 py-2 border border-bottom-0">{{report.author}}</div>
												<div class="text-primary px-3 py-2 border rounded-bottom">{{report.author.email}}</div>
											</div>
										</div>
										<div class="col">
											<div class="list-group">
												<div class="fw-bold text-uppercase small text-dark px-3 py-2 border border-bottom-0 rounded-top">Conducteur</div>
												<div class="text-primary px-3 py-2 border border-bottom-0">{{report.participation.ride.driver}}</div>
												<div class="text-primary px-3 py-2 border rounded-bottom">{{report.participation.ride.driver.email}}</div>
											</div>
										</div>
									</div>

									<hr>

									{% set ride = report.participation.ride %}
									<div class="text-center text-dark fs-4">{{ride.departureCity}}
										->
										{{ride.arrivalCity}}</div>
									<div class="row align-items-center mx-auto">
										<div class="col fs-5 text-dark text-end">{{ ride.departureTime|date('H:i') }}</div>
										<div class="col-6 line"></div>
										<div class="col fs-5 text-dark">{{ ride.arrivalTime|date('H:i') }}</div>
									</div>

									<hr>
                                        <h5 class="text-dark">Description du litige :</h5>
                                        <div>
                                            <p class="text-secondary">{{report.description}}</p>
                                        </div>
                                    <hr>
									<div class="d-flex flex-column flex-md-row justify-content-center gap-3">
										<form method="post" action="{{ path('app_reports_refund', {id: report.id}) }}" onsubmit="return confirm('Vous vous apprêtez à rembourser le passager. Êtes-vous sûre ?');">
											<input type="hidden" name="_token" value="{{ csrf_token('app_reports_' ~ report.id) }}">
											<button class="btn btn-outline-success w-100" type="submit">
												<i class="bi bi-check-circle me-2"></i>Rembourser {{report.participation.creditsUsed}}<i class="bi bi-coin text-warning ms-1"></i>
											</button>
										</form>
										<form method="post" action="{{ path('app_reports_decline', {id: report.id}) }}" onsubmit="return confirm('En rejetant le litige le conducteur recevra ses jetons et le passager ne sera pas remboursé. Êtes-vous sûre ?');">
											<input type="hidden" name="_token" value="{{ csrf_token('app_reports_decline' ~ report.id) }}">
											<button class="btn btn-outline-danger w-100" type="submit">
												<i class="bi bi-exclamation-octagon me-2"></i>Rejeter litige
											</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			{% else %}
				<div class="text-primary text-center">Aucun litige à gérer pour le moment.</div>
			{% endif %}
		</section>
	</main>

{% endblock %}

app/templates/dashboard/employe/manage-reviews.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les avis - EcoRde
{% endblock %}

{% block body %}

	<main class="container-xl">
		<a href="{{path('app_dashboard')}}" class="btn text-dark">
			<i class="bi bi-arrow-left-circle fs-3"></i>
		</a>
		<h1 class="text-dark">Gérer les avis</h1>

		<section class="mt-3">
			{% if reviews is not empty %}
			<div class="accordion mt-3" id="accordion_reviews">
				{% for review in reviews %}
					<div class="accordion-item">
						<h2 class="accordion-header" id="heading-{{ loop.index }}">
							{% set is_first = loop.first %}
							<button class="accordion-button {{ is_first ? '' : 'collapsed'}}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ loop.index }}" aria-expanded="{{ is_first ? 'true' : 'false' }}" aria-controls="collapse-{{ loop.index }}">
								Avis de
								<span class='text-primary mx-1'>{{review.author}}</span>
								à
								<span class='text-primary mx-1'>{{review.target}}</span>
							</button>
						</h2>
						<div id="collapse-{{ loop.index }}" class="accordion-collapse collapse {{ is_first ? 'show' : '' }}" data-bs-parent="#accordion_reviews">
							<div class="accordion-body">
								<h5 class="text-primary">Trajet numéro :
									{{review.ride.id}}</h5>
								<div class="d-flex mb-2">
									{% for i in 1..5 %}
										{% if i <= review.rating %}
											<i class="bi bi-star-fill text-warning"></i>
										{% else %}
											<i class="bi bi-star text-warning"></i>
										{% endif %}
									{% endfor %}
								</div>
								<div>{{review.comment}}</div>
								<hr>
								<div class="d-flex flex-column flex-md-row justify-content-center gap-3">
									<form method="post" action="{{ path('app_valid_review', {id: review.id}) }}">
										<input type="hidden" name="_token" value="{{ csrf_token('app_valid_review' ~ review.id) }}">
										<button class="btn btn-outline-success w-100" type="submit">
											<i class="bi bi-check-circle me-2"></i>Valider avis
										</button>
									</form>
									<form method="post" action="{{ path('app_reject_review', {id: review.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet avis ?');">
										<input type="hidden" name="_token" value="{{ csrf_token('app_reject_review' ~ review.id) }}">
										<button class="btn btn-outline-danger w-100" type="submit">
											<i class="bi bi-exclamation-octagon me-2"></i>Rejeter avis
										</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			{% else %}
				<div class="text-primary text-center">Aucun avis à gérer pour le moment.</div>
			{% endif %}
		</section>
	</main>

{% endblock %}