app/src/Entity/Ride.php
<?php

namespace App\Entity;

use App\Repository\RideRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RideRepository::class)]
class Ride
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $departure_city = null;

    #[ORM\Column(length: 255)]
    private ?string $departure_address = null;

    #[ORM\Column(length: 10)]
    private ?string $departure_post_code = null;

    #[ORM\Column(length: 255)]
    private ?string $arrival_city = null;

    #[ORM\Column(length: 255)]
    private ?string $arrival_address = null;

    #[ORM\Column(length: 10)]
    private ?string $arrival_post_code = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $departure_time = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $arrival_time = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $seats_available = null;

    #[ORM\Column]
    private ?bool $ecological = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $driver = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicle $vehicle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepartureCity(): ?string
    {
        return $this->departure_city;
    }

    public function setDepartureCity(string $departure): static
    {
        $this->departure_city = $departure;

        return $this;
    }
    
    public function getDepartureAddress(): ?string
    {
        return $this->departure_address;
    }

    public function setDepartureAddress(string $departure): static
    {
        $this->departure_address = $departure;

        return $this;
    }

    public function getArrivalCity(): ?string
    {
        return $this->arrival_city;
    }

    public function setArrivalCity(string $arrival): static
    {
        $this->arrival_city = $arrival;

        return $this;
    }

public function getArrivalAddress(): ?string
    {
        return $this->arrival_address;
    }

public function setArrivalAddress(string $arrival): static
    {
        $this->arrival_address = $arrival;

        return $this;
    }

    public function getDepartureTime(): ?\DateTimeImmutable
    {
        return $this->departure_time;
    }

    public function setDepartureTime(\DateTimeImmutable $departure_time): static
    {
        $this->departure_time = $departure_time;

        return $this;
    }

    public function getArrivalTime(): ?\DateTimeImmutable
    {
        return $this->arrival_time;
    }

    public function setArrivalTime(\DateTimeImmutable $arrival_time): static
    {
        $this->arrival_time = $arrival_time;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getSeatsAvailable(): ?int
    {
        return $this->seats_available;
    }

    public function setSeatsAvailable(int $seats_available): static
    {
        $this->seats_available = $seats_available;

        return $this;
    }

    public function isEcological(): ?bool
    {
        return $this->ecological;
    }

    public function setEcological(bool $ecological): static
    {
        $this->ecological = $ecological;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDriver(): ?User
    {
        return $this->driver;
    }

    public function setDriver(?User $driver): static
    {
        $this->driver = $driver;

        return $this;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): static
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    public function getDeparturePostCode(): ?string
    {
        return $this->departure_post_code;
    }
    
    public function setDeparturePostCode(string $departure_post_code): static
    {
        $this->departure_post_code = $departure_post_code;
    
        return $this;
    }

    public function getArrivalPostCode(): ?string
    {
        return $this->arrival_post_code;
    }
    
    public function setArrivalPostCode(string $arrival_post_code): static
    {
        $this->arrival_post_code = $arrival_post_code;
    
        return $this;
    }
}

app/src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehicleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[UniqueEntity(fields: ['plate'], message: 'Cette plaque est déjà utilisée.')]
#[ORM\Entity(repositoryClass: VehicleRepository::class)]
class Vehicle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $plate = null;

    #[ORM\Column(length: 255)]
    private ?string $color = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $first_registration_date = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?CarModel $car_model = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isArchived = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlate(): ?string
    {
        return $this->plate;
    }

    public function setPlate(string $plate): static
    {
        $this->plate = $plate;

        return $this;
    }

    public function __toString(): string
    {
        return $this->plate . ' - ' . $this->car_model->getLabel();
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function getFirstRegistrationDate(): ?\DateTimeInterface
    {
        return $this->first_registration_date;
    }

    public function setFirstRegistrationDate(\DateTimeInterface $first_registration_date): static
    {
        $this->first_registration_date = $first_registration_date;

        return $this;
    }

    public function getCarModel(): ?CarModel
    {
        return $this->car_model;
    }

    public function setCarModel(?CarModel $car_model): static
    {
        $this->car_model = $car_model;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function isArchived(): bool
    {
        return $this->isArchived;
    }

    public function setIsArchived(bool $isArchived): static
    {
        $this->isArchived = $isArchived;
        return $this;
    }
}

app/src/Controller/RideDetailsController.php
<?php

namespace App\Controller;

use App\Document\DriverPreference;
use App\Entity\Ride;
use App\Repository\ReviewRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class RideDetailsController extends AbstractController
{
    #[Route('/ride/{id}/details', name: 'app_ride_details', methods:['GET'])]
    public function index(
        Ride $ride,
        DocumentManager $dm,
        ReviewRepository $reviewRepository,
    ): Response
    {
        $driver = $ride->getDriver();
        $user = $this->getUser();

        $preferences = $dm->getRepository(DriverPreference::class)->findOneBy([
            'userId' => $driver->getId(),
        ]);

        $driverRating = $reviewRepository->getAverageRatingForUser($driver);
        $numberOfReviewsDriver = $reviewRepository->findBy([
            'target' => $driver,
            'validated' => true,
        ]);

        return $this->render('ride_details/index.html.twig', [
            'ride' => $ride,
            'preferences' => $preferences,
            'driver_rating' => $driverRating,
            'number_of_reviews_driver' => $numberOfReviewsDriver,
            'user' => $user,
        ]);
    }
}

app/templates/ride_details/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du trajet - EcoRide
{% endblock %}

{% block body %}
	<main class="container-xl">
		<button onclick="window.history.back()" class="btn text-dark">
			<i class="bi bi-arrow-left-circle fs-3"></i>
		</button>
		<h1 class="text-dark mb-3">Détail du trajet</h1>

		<div class="row justify-content-center">
			<section class="col-12 col-md-10 col-lg-6 align-self-start mb-3">
				<div class="bg-white rounded shadow overflow-hidden">
					<div class="row align-items-center p-3">
						<span class="text-primary col fs-4">{{ride.departureCity}}
							->
							{{ride.arrivalCity}}</span>
						<span class="text-end text-primary col fs-4">{{ride.departureTime|date('d/m/Y')}}</span>
					</div>
					<hr class="mt-0">
					<div class="row align-items-center px-3 py-2">
						<div class="d-flex align-items-center col">
							<img src="{{ asset(ride.driver.photo ?? '/assets/images/user.png') }}" alt="Photo de profil" class="img-fluid rounded-circle border border-3 border-primary me-2" style="width: 60px; height: 60px; object-fit: cover;">
							<div class="fs-5">{{ride.driver}}</div>
						</div>
						<div class="col text-end">
							{% if driver_rating is defined and driver_rating > 0 %}
								<p class="mb-0">{{ driver_rating|number_format(1) }}/5
									<i class="bi bi-star-fill text-warning"></i>
								</p>
							{% else %}
								<p class="text-muted">Pas encore noté</p>
							{% endif %}
						</div>
					</div>
					<hr>
					<div class="row align-items-center mx-auto px-3 py-2">
						<div class="col fs-5 text-dark text-end">{{ride.departureTime|date('H:m')}}</div>
						<div class="col-6 line"></div>
						<div class="col fs-5 text-dark">{{ride.arrivalTime|date('H:m')}}</div>
					</div>
					<hr>
					<div class="row align-items-center mx-auto px-3 py-2">
						<div class="col-8">
							{% if ride.vehicle.carModel.energy == 'electric'%}
								<p class="text-secondary mb-0">Voyage écologique
									<i class="bi bi-lightning-charge"></i>
								</p>
							{% endif %}
							<p class="mb-0">Places restante(s) :
								{{ride.seatsAvailable}}</p>
						</div>
						<div class="text-dark col text-end ">
							<span class="fs-4">
								{{ride.price}}
								<i class="bi bi-coin text-warning"></i>
							</span>
						</div>
					</div>
                    {% if user and user == ride.driver %}
                    {% else %}
					<form method="POST" action="{{ path('participations_book', { id: ride.id }) }}" onsubmit="return confirm('Êtes vous sur de vouloir réserver ce trajet ?');">
						<input type="hidden" name="_token" value="{{ csrf_token('participations_book_' ~ ride.id) }}">
						<button class="btn btn-primary w-100 rounded-0 rounded-bottom py-3">Réserver</button>
					</form>
                    {% endif %}
                    
				</div>
			</section>
			<section class="col-12 col-md-10 col-lg-6 mx-auto">
				<div class="my-3 d-flex">
					<h5 class="text-primary me-2">
						<i class="bi bi-geo-alt"></i>Départ :</h5>
					<span class="text-dark">{{ride.departureAddress}}</span>
				</div>
				<hr>
				<div class="my-3 d-flex">
					<h5 class="text-primary me-2">
						<i class="bi bi-geo-alt"></i>Arrivée :</h5>
					<span class="text-dark">{{ride.arrivalAddress}}</span>
				</div>
				<hr>
				<a href="{{path('app_driver_reviews', { pseudo: ride.driver.pseudo|url_encode })}}" class="text-decoration-none">
					<div class="d-flex my-3 text-dark">
						<h5 class="text-primary me-2">Avis({{number_of_reviews_driver|length}}) :
						</h5>
						{% if driver_rating is defined and driver_rating > 0 %}
							<p class="mb-0">{{ driver_rating|number_format(1) }}/5
								<i class="bi bi-star-fill text-warning"></i>
							</p>
						{% else %}
							<p class="text-muted">Pas encore noté</p>
						{% endif %}
						<i class="bi bi-chevron-right text-dark col text-end"></i>
					</div>
				</a>
				<hr>

				<div class="my-3 d-flex">
					<h5 class="text-primary me-2">Véhicule du trajet :</h5>
					{% if ride.vehicle.carModel.energy == 'electric'%}
						<span class="text-primary">
							<i class="bi bi-lightning-charge"></i>
							{{ride.vehicle.carModel.brand.label}}
							-
							{{ride.vehicle.Carmodel.label}}
						</span>
					{% else %}
						<span class="text-dark">
							{{ride.vehicle.carModel.brand.label}}
							-
							{{ride.vehicle.Carmodel.label}}
						</span>
					{% endif %}
				</div>

				<hr>

				<div class="my-3 row justify-content-center">
					<div class="col-12 col-md-6">
						<h5 class="text-dark">Préférences conducteur</h5>
						<div class="mb-3">
							<div class="d-flex justify-content-between align-items-center border rounded p-2 mb-2 shadow-sm {{ preferences.musicAllowed ? 'text-success border-success' : 'text-danger border-danger'}}">
								<span>Musique</span>
								<i class="bi bi-hand-thumbs-{{ preferences.musicAllowed ? 'up' : 'down'}}"></i>
							</div>
							<div class="d-flex justify-content-between align-items-center border rounded p-2 mb-2 shadow-sm {{ preferences.smokingAllowed ? 'text-success border-success' : 'text-danger border-danger'}}">
								<span>Fumer</span>
								<i class="bi bi-hand-thumbs-{{ preferences.smokingAllowed ? 'up' : 'down'}}"></i>
							</div>
							<div class="d-flex justify-content-between align-items-center border rounded p-2 mb-2 shadow-sm {{ preferences.animalsAllowed ? 'text-success border-success' : 'text-danger border-danger'}}">
								<span>Animaux</span>
								<i class="bi bi-hand-thumbs-{{ preferences.animalsAllowed ? 'up' : 'down'}}"></i>
							</div>

						</div>
					</div>
					<div class="col-12 col-md-6">
						<h5 class="text-dark">Demandes du conducteur</h5>
						<div class="mb-3">
							{% for customPreference in preferences.customPreferences %}
								<div class="d-flex justify-content-between align-items-center border rounded p-2 mb-2 shadow-sm text-dark border-dark">
									<span>{{customPreference}}</span>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</main>{% endblock %}